apiVersion: apps/v1
kind: Deployment

metadata:
  name: helm-test-app
  labels:
    app: helm-test-app

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helm-test-app
  template:
    metadata:
      labels:
        app: helm-test-app
    spec:
      containers:
      - name: helm-test-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        
        ports:
        - containerPort: {{ .Values.port }}

        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
